# Generated by Django 5.0 on 2023-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiqa', '0002_alter_albom_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshiq',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
